Development
metamaze/enrichments pull request #2
Opened 2021-07-09 07:15 UTC by hasansalimkanmaz

2021-07-09 10:37 UTC, AntPeixe requested changes
the templates/test folder can also be removed in this example code

2021-07-09 10:37 UTC, AntPeixe commented on ActionMappingEnrichment/requirements.txt
> +# formatting
maybe these formatting requirements can be moves to the root of the repo since you are adding the configs there

2021-07-09 10:37 UTC, AntPeixe commented on ActionMappingEnrichment/server.py
> +def check_token(f):
if this is exactly the same then maybe should consider moving function to a util package.
can be done later if another enrichment is created

2021-07-09 10:37 UTC, AntPeixe commented on PythonFlaskAirtableEnrichment/requirements.txt
> +# formatting
same as the above comment

2021-07-19 15:56 UTC, JosPolfliet commented on ActionMappingEnrichment/README.md
> +This is an example data enrichment to classify free-form inspection points to specific action codes for the Metamaze Intelligent Document Processing platform. This enrichment uses a simple Flask API
Can you make all copy-writing more generic:
- Change "action mapping" into "text classification"
- Change "app.ordered_actions" to "ordered_classes".

We publish this example as open source so want it as generic as possible.

2021-07-19 16:01 UTC, JosPolfliet reviewed
I wonder if we should add a stub for training too (without the - inherently project specific - data integration code) to show a full example. Can just be a jupyter notebook or whatever you used that just shows 1) embedding the examples 2) training RF model 3) saving the files

2021-07-19 16:01 UTC, JosPolfliet commented on ActionMappingEnrichment/server.py
> +    # do NOT run this is prod, flask dev server is not meant for that
text typo `... run this IN prod ...`

2021-07-19 16:02 UTC, JosPolfliet commented on ActionMappingEnrichment/server.py
> +    with open("classifier.pkl", "rb") as f:
We'll need to figure out a way to add the classifier.pkl somewhere without publicly exposing it on GitHub. Not sure yet how.

2021-07-19 16:04 UTC, hasansalimkanmaz commented on ActionMappingEnrichment/server.py
> +    with open("classifier.pkl", "rb") as f:
It is not exposed. Only the name can be seen here. All `pkl` files will be ignored by `.gitignore`

2021-07-19 18:10 UTC, JosPolfliet commented on ActionMappingEnrichment/server.py
> +    with open("classifier.pkl", "rb") as f:
Ok I see. And then we build and push the Dockerfile manually (compiling your local classifier.pkl into it) to the registry instead of using CI/CD? Since it will likely almost never change that seems good approach indeed.

2021-07-20 18:31 UTC, JosPolfliet commented on TextClassificationEnrichment/config.py
> +BEARER_TOKEN = os.environ["BEARER_TOKEN"]  # Configured in Metamaze Project Settings
maybe not worth having a separate file for if it is only this line 🤷

2021-07-26 16:03 UTC, merged